version: '3.8'

services:
  app:
    image: php:8.2-cli
    container_name: php_app
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    environment:
      - COMPOSER_HOME=/composer
    networks:
      - app-network
    command: bash -c "composer install && ./vendor/bin/phpunit --configuration phpunit.xml"

  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
