name: PHPUnit Tests

on:
  # Trigger the workflow on pull requests to the main branch
  pull_request:
    branches:
      - main

  # Allow the workflow to be triggered manually
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: redis

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run PHPUnit tests
        run: composer test

      - name: Upload PHPUnit coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: build/coverage-html
